// Skeleton class generated by rmic, do not edit.
// Contents subject to change without notice.

public final class PrinterMachine_Skel
    implements java.rmi.server.Skeleton
{
    private static final java.rmi.server.Operation[] operations = {
	new java.rmi.server.Operation("int getCount()"),
	new java.rmi.server.Operation("int getLocation()"),
	new java.rmi.server.Operation("State getState()")
    };
    
    private static final long interfaceHash = -5260438444927807617L;
    
    public java.rmi.server.Operation[] getOperations() {
	return (java.rmi.server.Operation[]) operations.clone();
    }
    
    public void dispatch(java.rmi.Remote obj, java.rmi.server.RemoteCall call, int opnum, long hash)
	throws java.lang.Exception
    {
	if (hash != interfaceHash)
	    throw new java.rmi.server.SkeletonMismatchException("interface hash mismatch");
	
	PrinterMachine server = (PrinterMachine) obj;
	switch (opnum) {
	case 0: // getCount()
	{
	    call.releaseInputStream();
	    int $result = server.getCount();
	    try {
		java.io.ObjectOutput out = call.getResultStream(true);
		out.writeInt($result);
	    } catch (java.io.IOException e) {
		throw new java.rmi.MarshalException("error marshalling return", e);
	    }
	    break;
	}
	    
	case 1: // getLocation()
	{
	    call.releaseInputStream();
	    int $result = server.getLocation();
	    try {
		java.io.ObjectOutput out = call.getResultStream(true);
		out.writeInt($result);
	    } catch (java.io.IOException e) {
		throw new java.rmi.MarshalException("error marshalling return", e);
	    }
	    break;
	}
	    
	case 2: // getState()
	{
	    call.releaseInputStream();
	    State $result = server.getState();
	    try {
		java.io.ObjectOutput out = call.getResultStream(true);
		out.writeObject($result);
	    } catch (java.io.IOException e) {
		throw new java.rmi.MarshalException("error marshalling return", e);
	    }
	    break;
	}
	    
	default:
	    throw new java.rmi.UnmarshalException("invalid method number");
	}
    }
}
